services:

  roller:
    image: ghcr.io/eldisgustin/foundry-discord-dice-roller
    restart: unless-stopped
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}