services:

  roller:
    image: eldisgustin/foundryvtt-discord-dice-roller
    restart: unless-stopped
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db